services:
  db:
    image: mysql:8
    container_name: uber_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uber_clone
      MYSQL_USER: uber_user
      MYSQL_PASSWORD: uber_pass
    ports: 
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: uber_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8880:80"
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: uber_redis
    ports: ["6379:6379"]

  api:
    build: .
    image: uber-backend:dev
    container_name: uber_api
    command: npm run start:dev
    ports: ["3000:3000"]
    env_file: .env.dev
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on: [db, redis]

volumes:
  mysqldata:
